let data = [
  {
    id: 1,
    name: "Shirts",
    type: "men",
    img_src: "./images/1.png",
    price: 250.0,
    count: 1,
  },
  {
    id: 2,
    name: "Printed T-Shirts",
    type: "men",
    img_src: "./images/2.png",
    price: 300.0,
    count: 1,
  },
  {
    id: 3,
    name: "Plain T-Shirt",
    type: "men",
    img_src: "./images/3.png",
    price: 320.0,
    count: 1,
  },
  {
    id: 4,
    name: "Polo T-Shirt",
    type: "men",
    img_src: "./images/4.png",
    price: 330.0,
    count: 1,
  },
  {
    id: 5,
    name: "Hoodies & Sweetshirt",
    type: "men",
    img_src: "./images/5.png",
    price: 400.0,
    count: 1,
  },
  {
    id: 6,
    name: "Jeans",
    type: "men",
    img_src: "./images/6.png",
    price: 220.0,
    count: 1,
  },
  {
    id: 7,
    name: "Activewear",
    type: "men",
    img_src: "./images/7.png",
    price: 400.0,
    count: 1,
  },
  {
    id: 8,
    name: "Boxers",
    type: "men",
    img_src: "./images/8.png",
    price: 120.0,
    count: 1,
  },
  {
    id: 9,
    name: "Active T-Shirts",
    type: "men",
    img_src: "./images/9.png",
    price: 400.0,
    count: 1,
  },
  {
    id: 10,
    name: "Full Sleeve",
    type: "men",
    img_src: "./images/10.png",
    price: 450.0,
    count: 1,
  },
  {
    id: 11,
    name: "Hoodies & Sweetshirt",
    type: "women",
    img_src: "./images/11.png",
    price: 400.0,
    count: 1,
  },
  {
    id: 12,
    type: "women",
    name: "Coats & Parkas",
    img_src: "./images/12.png",
    price: 650.0,
    count: 1,
  },
  {
    id: 13,
    name: "Tees & T-Shirt",
    img_src: "./images/13.png",
    price: 400.0,
    count: 1,
  },
  {
    id: 14,
    name: "Boxers",
    img_src: "./images/14.png",
    price: 130.0,
    count: 1,
  },
  {
    id: 15,
    type: "women",
    name: "Black Sweatshirt with ...",
    img_src: "./images/15.png",
    price: 250.0,
    count: 1,
  },
  {
    id: 16,
    type: "women",
    name: "line Pattern Black H...",
    img_src: "./images/16.png",
    price: 220.0,
    count: 1,
  },
  {
    id: 17,
    type: "women",
    name: "Black Shorts",
    img_src: "./images/17.png",
    price: 270.0,
    count: 1,
  },
  {
    id: 18,
    type: "women",
    name: "Levender Hoodie with ....",
    img_src: "./images/18.png",
    price: 380.0,
    count: 1,
  },
];
