let data = [
  {
    id: 1,
    name: "Shirts",
    type: "men",
    img_src: "./images/1.png",
    salary: 250.0 + "$",
  },
  {
    id: 2,
    name: "Printed T-Shirts",
    type: "men",
    img_src: "./images/2.png",
    salary: 300.0 + "$",
  },
  {
    id: 3,
    name: "Plain T-Shirt",
    type: "men",
    img_src: "./images/3.png",
    salary: 320.0 + "$",
  },
  {
    id: 4,
    name: "Polo T-Shirt",
    type: "men",
    img_src: "./images/4.png",
    salary: 330.0 + "$",
  },
  {
    id: 5,
    name: "Hoodies & Sweetshirt",
    type: "men",
    img_src: "./images/5.png",
    salary: 400.0 + "$",
  },
  {
    id: 6,
    name: "Jeans",
    type: "men",
    img_src: "./images/6.png",
    salary: 220.0 + "$",
  },
  {
    id: 7,
    name: "Activewear",
    type: "men",
    img_src: "./images/7.png",
    salary: 400.0 + "$",
  },
  {
    id: 8,
    name: "Boxers",
    type: "men",
    img_src: "./images/8.png",
    salary: 120.0 + "$",
  },
  {
    id: 9,
    name: "Active T-Shirts",
    type: "men",
    img_src: "./images/9.png",
    salary: 400.0 + "$",
  },
  {
    id: 10,
    name: "Full Sleeve",
    type: "men",
    img_src: "./images/10.png",
    salary: 450.0 + "$",
  },
  {
    id: 11,
    name: "Hoodies & Sweetshirt",
    type: "women",
    img_src: "./images/11.png",
    salary: 400.0 + "$",
  },
  {
    id: 12,
    type: "women",
    name: "Coats & Parkas",
    img_src: "./images/12.png",
    salary: 650.0 + "$",
  },
  {
    id: 13,
    name: "Tees & T-Shirt",
    img_src: "./images/13.png",
    salary: 400.0 + "$",
  },
  { id: 14, name: "Boxers", img_src: "./images/14.png", salary: 130.0 + "$" },
  {
    id: 15,
    type: "women",
    name: "Black Sweatshirt with ...",
    img_src: "./images/15.png",
    salary: 250.0 + "$",
  },
  {
    id: 16,
    type: "women",
    name: "line Pattern Black H...",
    img_src: "./images/16.png",
    salary: 220.0 + "$",
  },
  {
    id: 17,
    type: "women",
    name: "Black Shorts",
    img_src: "./images/17.png",
    salary: 270.0 + "$",
  },
  {
    id: 18,
    type: "women",
    name: "Levender Hoodie with ....",
    img_src: "./images/18.png",
    salary: 380.0 + "$",
  },
];
